services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vishwas_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0 --port 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENV: dev
    container_name: vishwas_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:cached
      - ./backend/google-credentials.json:/secrets/google-credentials.json:ro
